itbench-hub/ITBench-Scenarios

.github/dependabot.yml
sre/tools/elasticsearch-dummy-app/Dockerfile
sre/tools/kubernetes-topology-mapper/Dockerfile

This PR adds Dependabot updates for the Docker images used by SRE scenarios.

feat: add dependabot updates for Docker images

---

.github/dependabot.yml

This is a follow up PR to #25 so that the PRs are combined into one rather than individually.

fix: apply grouping to dependabot docker pull requests

---

.github/dependabot.yml
sre/tools/elasticsearch-dummy-app/Dockerfile
sre/tools/elasticsearch-dummy-app/requirements.txt

Continuing #25 by adding the rest of the package ecosystems for SRE Scenarios.

feat: add Dependabot for python and golang dependencies

---

README.md
sre/base.yaml
sre/local_cluster/README.md
sre/local_cluster/README_RHEL.md
sre/roles/observability_tools/tasks/install_elasticsearch.yaml
sre/roles/sample_applications/tasks/install_astronomy_shop.yaml

while running locally on Kind clusters on both Mac (arm64) and Linux (amd64). OOMKilled was being observed even before a fault was injected. Also added the requirement to have GoLang v1.24 and above for the local cluster setup. Anything below does not work as the `tool` directive is only supported in Golang v1.24 and above.

fix: update Astronomy Shop resource limits to avoid OOM errors

---

.pre-commit-config.yaml

This PR is a followup form #41 . It updates the `pre-commit` configuration to use the same  version of `commitizen`.

chore: sync precommit commitizen version

---

.github/dependabot.yml

This is a follow up PR to #40 . This corrects the directory details for Dependabot to scan the CISO scenario's Dockerfile.

fix: correct directory location of CISO scenarios Dockerfile

---

sre/group_vars/observability_tools.yaml
sre/roles/book_keeping/tasks/leverage_ingress.yaml
sre/roles/book_keeping/tasks/main.yaml
sre/roles/bundle_info/tasks/main.yaml
sre/roles/evaluation/tasks/fetch_alerts.yaml
sre/roles/fault_injection/tasks/run_missing_storageclass.yaml
sre/roles/observability_tools/tasks/install_elasticsearch.yaml
sre/roles/observability_tools/tasks/install_jaeger.yaml
sre/roles/observability_tools/tasks/install_opencost.yaml
sre/roles/observability_tools/tasks/install_prometheus.yaml
sre/roles/observability_tools/templates/datasource_prometheus.j2
sre/roles/observability_tools/templates/prometheus-alerting-rules.j2
sre/roles/observability_tools/templates/prometheus-recording-rules.j2
sre/roles/sample_applications/tasks/install_astronomy_shop.yaml
sre/roles/sample_applications/tasks/install_deathstarbench_hotel_reservation.yaml

This PR changes the Prometheus Helm chart from the community's `kube-prometheus-stack` (which deploys the Prometheus Operator to manage a Prometheus instance) to `prometheus`. This removes the operator, which would not be necessary considering the short nature of the benchmarks.

feat: switch from kube-prometheus-stack chart to prometheus chart

---

CONTRIBUTING.md

This PR updates the instructions for installing `pre-commit` hooks so that `commitizen` will run on a fresh installation.

docs(CONTRIBUTING.md): update pre-commit install instructions 

---

sre/remote_cluster/README.md
sre/remote_cluster/playbooks/batch_variables.yaml.example
sre/remote_cluster/playbooks/variables.yaml.example

This PR removes the reference to the `ansible_python_interpreter` variable in the `remote_cluster` directory. When using Python virtual environments, the interpreter picks up the Python executable used in said environment. Thus, there is no need to overwrite or direct it to do so.

refactor: remove references to ansible_python_interpreter

---

.cz.toml
CHANGELOG.md

This PR adds a `CHANGELOG.md` file with an entry describing the v0.0.1 pre-release.

docs(CHANGELOG.md): add entry for v0.0.1 and v0.0.2 pre-release 

---

.github/dependabot.yml
.github/workflows/sre-build-push-images.yaml
sre/tools/astronomy-shop-checkout-service/Dockerfile
sre/tools/kubernetes-topology-mapper/charts/kubernetes-topology-mapper/templates/deployment.yaml

This PR adds a GitHub action to build and push the topology mapper tools to the image repository.

feat: add docker build-push actions for SRE scenario tools

---

.github/workflows/sre-build-push-images.yaml
sre/tools/kubernetes-topology-mapper/charts/kubernetes-topology-mapper/templates/deployment.yaml

This PR updates the SRE tool docker tags to v0.0.2

bump: update sre tools docker image tags to v0.0.2

---

.pre-commit-config.yaml

This PR updates the `pre-commit` `commitizen` tool to the latest after #74 .

chore: update pre-commit commitizen check

---

.github/dependabot.yml

This PR updates the dependabot configuration to use groups. It also updates the checks for al components to be at the daily interval.

chore: update dependabot configuration with groups

---

.github/dependabot.yml
.github/workflows/sre-build-push-tools.yaml
sre/roles/fault_injection/tasks/run_unsupported_image.yaml
sre/tools/kubernetes-topology-mapper/Dockerfile
sre/tools/kubernetes-topology-mapper/charts/kubernetes-topology-mapper/templates/deployment.yaml
sre/tools/kubernetes-topology-mapper/requirements.txt

This PR updates the `kubernetes-topology-mapper` tool to be built from the minimal ubi9 image. This allows the final build image to be smaller and only contain the minimal amount of needed software.

chore: update base image of topology mapper to minimal ubi9 image

---

.github/dependabot.yml
sre/group_vars/fault_injection.yaml
sre/group_vars/observability_tools.yaml
sre/roles/fault_injection/tasks/install_chaos_mesh.yaml
sre/roles/observability_tools/tasks/install_opentelemetry.yaml
sre/tools/kubernetes-topology-mapper/charts/kubernetes-topology-mapper/templates/deployment.yaml

This PR updates the `observability` and `fault` tools to their latest versions. In addition, it also changes the `Dependabot` check frequency and updates the dependencies in the topology mapper.

bump: update observability and fault tools

---

sre/group_vars/documentation.yaml
sre/roles/documentation/defaults/main/incidents_schema.yaml
sre/roles/documentation/tasks/collect_documentation.yaml

adds validation of `Alert Names / IDs` in `make documentation`. Alternate to #84 in a way. Wondering if #84 at this point could simply call `make documentation` as there are already a number of other checks in place there-in.

chore: add alert name validation for incident ground truth documentation

---

sre/roles/observability_tools/tasks/install_ingress.yaml
sre/roles/observability_tools/tasks/install_opencost.yaml
sre/roles/observability_tools/tasks/install_prometheus.yaml

This PR adds `Content-Security-Policy` and other headers to the traffic handled by Ingress.

fix: add Content-Security-Policy headers to Ingress traffic

---

.github/workflows/sre-integration-smoke-tests.yaml

This PR adds concurrency rules for the integration tests, namely that they be cancelled if there is a new push to a branch.

chore: add concurrency rules for integration tests

---

sre/DEVELOPER_GUIDE.md
sre/docs/applications.md
sre/docs/tools.md

This PR updates the documentation to provide instructions on how developers and practitioners can contribute to ITBench for the SRE and FinOps domains.

docs: update contribution instructions

---

sre/dev/remote_cluster/Makefile
sre/dev/remote_cluster/roles/awx/tasks/create_async.yaml
sre/dev/remote_cluster/roles/awx/tasks/export.yaml
sre/dev/remote_cluster/roles/awx/tasks/main.yaml

This PR adds new functionality to export all the kubeconfigs used for the AWX stack. This is available through the new `make export_awx_kubeconfigs` command. This command also updates the `stack.yaml` group variable file with the kubeconfigs to simplify set up.

feat: add export command for AWX clusters kubeconfigs
